language: python

install:
    - cd ~
    - git clone --depth=1 https://github.com/MTGos/cross-compilers opt
    - |
        CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
        mkdir -p cmake &&
        travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
        export PATH="~/cmake/bin:$PATH"
    - cd -

python:
    - "3.4"

script:
    - bash do_all.sh
    - cd out

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    target_branch: kernel
    repo: https://github.com/MTGos/nightlies

